---
# tasks file for search
- file:
    state: directory
    path: /opt/solr
- get_url:
    url: https://apache.inspire.net.nz/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz
    dest: /opt/solr
- unarchive:
    src: /opt/solr/solr-{{solr_version}}.tgz
    dest: /opt/solr/
    remote_src: yes
- apt:
    name: openjdk-11-jre
    state: present
  when: ansible_facts.os_family == 'Debian'
- yum:
    name: java-11-openjdk
    state: present
  when: ansible_facts.os_family == 'RedHat'
  #install configuration files
  #install a systemd unit
  #start jetty server