---
- hosts: thinkcentre
  become: yes
  become_method: sudo
  tasks:
    - name: download cloudflared deb
      become: no
      get_url:
          dest: files/cloudflared-stable-linux-amd64.deb # required. Absolute path of where to download the file to.,If C(dest) is a directory, either the server provided filename or, if none provided, the base name of the URL on the remote server will be used. If a directory, C(force) has no effect.,If C(dest) is a directory, the file will always be downloaded (regardless of the C(force) option), but replaced only if the contents changed..
          url: https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb # required. HTTP, HTTPS, or FTP URL in the form (http|https|ftp)://[user[:pass]]@host.domain[:port]/path
      delegate_to: localhost
    - name: copy cloudflared
      copy:
          dest: /opt/cloudflared-stable-linux-amd64.deb # required. Remote absolute path where the file should be copied to. If I(src) is a directory, this must be a directory too. If I(dest) is a nonexistent path and if either I(dest) ends with "/" or I(src) is a directory, I(dest) is created. If I(src) and I(dest) are files, the parent directory of I(dest) isn't created: the task fails if it doesn't already exist.
          src: files/cloudflared-stable-linux-amd64.deb # not required. Local path to a file to copy to the remote server; can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to Rsync.
    - name:
      apt:
          deb: /opt/cloudflared-stable-linux-amd64.deb # not required. Path to a .deb package on the remote machine.,If :// in the path, ansible will attempt to download deb before installing. (Version added 2.1)
          state: present
