- hosts: docker
  become: true
  tasks:
  - name: enable docker deb source
    apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable # required. A source string for the repository.
        state: present # not required. choices: absent;present. A source string state.
        update_cache: yes # not required. Run the equivalent of C(apt-get update) when a change occurs.  Cache updates are run after making changes.
        mode: 0644 # not required. The octal mode for newly created files in sources.list.d
  - name: install docker compose and nginx
    apt: 
      name: [docker-compose,nginx]
  # enable docker
  #install docker CE: https://docs.docker.com/install/linux/docker-ce/debian/
  - name: install docker
    apt: 
      name: [docker-ce,docker-ce-cli,containerd.io]
  - name: download updated docker-compose version
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64
      dest: /tmp/docker-compose
  - name: move to bin dir
    copy:
      src: /tmp/docker-compose
      dest: /usr/bin/docker-compose
      mode: 0755
      remote_host: yes
