all:
  hosts:
    prodesk:
      ansible_host: 192.168.1.14
    thinkcentre:
      ansible_host: 192.168.1.22
    fitlet:
      ansible_host: 192.168.1.24 
    brix:
      ansible_host: 192.168.1.23
    mossman-pc:
      ansible_host: 192.168.1.40
  children:
    linux:
      hosts:
        prodesk:
        thinkcentre:
        fitlet:
        brix:
    windows:
      hosts:
        mossman-pc:
