all:
  hosts:
    # pi:
    #   ansible_host: 10.10.6.104
    prodesk:
      ansible_host: 192.168.1.14
    thinkcentre:
      ansible_host: 192.168.1.22
    fitlet:
      ansible_host: 192.168.1.24 
    brix:
      ansible_host: 192.168.1.23
  children:
    awx:
      hosts:
    docker:
      hosts:
    minecraft:
      hosts:
