all:
  hosts:
  children:
      awx:
        hosts:
          thinkcentre:
            ansible_host: 10.10.6.43
      minecraft:
        hosts:
          brix:
            ansible_host: 10.10.6.74