all:
  hosts:
    pi:
      ansible_host: 10.10.6.104
    prodesk:
      ansible_host: 10.10.6.116

  children:
      awx:
        hosts:
          thinkcentre:
            ansible_host: 10.10.6.43
            
      docker:
        hosts:
          fitlet:
            ansible_host: 10.10.6.75 
            
      minecraft:
        hosts:
          brix:
            ansible_host: 10.10.6.74
            