---
- hosts: [dnf_based:!vultrgw]
  become: true
  tasks:
    - name: install iscsid
      ansible.builtin.dnf:
        name: iscsi-initiator-utils
    - name: enable start iscsid
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: true