---
- hosts: thinkcentre
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - 192.168.1.14:9100
        - 192.168.1.22:9100
        - 192.168.1.24:9100 
        - 192.168.1.23:9100
        - 192.168.1.34:9182
        labels:
          env: home