---
- hosts: thinkcentre
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - 10.10.6.43:9100
        - 10.10.6.75:9100
        - 10.10.6.74:9100
        labels:
          env: home