---
- hosts: thinkcentre
  become: yes
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - 192.168.1.14:9100
        - 192.168.1.22:9100
        - 192.168.1.24:9100 
        - 192.168.1.23:9100
        - 192.168.1.40:9182
        - 192.168.1.22:8888
        labels:
          env: home
    prometheus_scrape_configs:
    - job_name: router-snmp
      static_configs:
      - targets:
        - 192.168.1.1  # SNMP device.
      metrics_path: /snmp
      params:
        module: [if_mib]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 192.168.1.24:9116 
    - job_name: "node-file-servicediscovery"
      file_sd_configs:
        - files:
            - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from `prometheus_targets
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]  # Look for a HTTP 200 response.
      scrape_interval: 24h
      static_configs:
        - targets:
          - https://blog.mountainmoss.nz   # blog
          - http://grafana.mountainmoss.nz # grafana
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "[::]:9115"  # The blackbox exporter's real hostname:port.
      