Vagrant.configure("2") do |config|
    
    config.vm.define "debian" do |debian|
        debian.vm.box = "debian/buster64"
        debian.vm.synced_folder ".", "/vagrant", type: "rsync"
        debian.vm.provision "ansible" do |ansible|
            ansible.playbook = "tests/test.yml"
            ansible.config_file = "tests/ansible.cfg"
        end
    end
    config.vm.define "centos" do |centos|
        centos.vm.box = "centos/8"
        centos.vm.provision "ansible" do |ansible|
            ansible.playbook = "tests/test.yml"
            ansible.config_file = "tests/ansible.cfg"
        end
    end
end