---
# tasks file for gitea

- name: ensure database is created
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: ensure no other user can access the database
  postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent

- name: enable tcp connections
  postgresql_pg_hba:
    dest: /etc/postgresql/{{pg_version}}/main/pg_hba.conf
    contype: host
    users: '{{dbuser}}'
    source: '{{ansible_default_ipv4.address}}'
    databases: '{{dbname}}'
    method: scram-sha-256
    create: true
  register: hba_conf
- name: restart postgres
  service:
    name: postgresql
    state: restarted
  when: hba_conf.changed