---
# tasks file for vector-agent
- include: "{{role_path}}/tasks/redhat.yml"
  when: ansible_os_family == "RedHat"
- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == "Debian"
- name: templates
  template:
    src: "{{role_path}}/templates/vector.toml.j2"
    dest: /etc/vector/vector.toml
  register: toml
- systemd:
    name: vector
    state: restarted
  when: toml.changed