- name: copy setup script
  copy:
    src: "{{role_path}}/files/bash.rpm.sh"
    dest: /tmp/bash.rpm.sh
    mode: u=rwx,g=r,o=r
- name: run setup script
  command: "/tmp/bash.rpm.sh"
- dnf:
    name: vector
    state: latest
    update_cache: yes