---
# tasks file for minecraft
- name: update
  apt:
    update_cache: yes
    upgrade: yes
- name: install java 8 runtime
  apt:
    name: [openjdk-8-jre, aptitude, zip, tar, gzip, tmux]
- name: 'download rclone for backups'
  get_url:
    url: https://downloads.rclone.org/rclone-current-linux-amd64.deb
    dest: /opt/rclone.deb
- name: Install rclone
  apt:
    deb: /opt/rclone.deb
- name: update CF every hour at 3 past
  cron:
    name: 'backup minecraft'
    job: "/usr/bin/rclone copy /opt/minecraft/world gdrive:/world-backup/"
    hour: '5'
