---
- name: ensure dir
  file:
    path: /web/firefly
    state: directory
    owner: firefly
    group: www-data
- name: firefly clone
  git: 
    repo: https://github.com/firefly-iii/firefly-iii.git
    dest: /web/firefly
    single_branch: yes
    version: '5.7.10'
# - name: composer install
#   command: 
#     cmd: composer install --prefer-dist --no-dev 
#     chdir: /web/firefly/
#     creates: /web/firefly/vendor/autoload.php
#sudo chmod -R 775 firefly-iii/storage
#setup database
- name: ensure dir
  file:
    path: /etc/mysql
    state: directory
- name: build my.cnf file
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
- name: create db user conf
  template:
    src: ../templates/firefly.cnf.j2
    dest: /home/firefly/.my.cnf
- name: start db
  service:
    name: mariadb
    state: started
    enabled: yes
- name: make db user
  command:
    cmd: "mysql -e \"CREATE USER IF NOT EXISTS 'firefly'@'localhost' IDENTIFIED BY '{{ db_password }}';\""
- name: make db
  command:
    cmd: "mysql -e \"CREATE DATABASE IF NOT EXISTS firefly CHARACTER SET utf8mb4\""
- name: set priviledges
  command:
    cmd: "mysql -e \" GRANT ALL PRIVILEGES ON firefly.* TO 'firefly'@'localhost';\""
- name: copy php fpm config
  copy:
    src: "../files/firefly-fpm.conf"
    dest: /etc/php/8.0/fpm/pool.d/firefly.conf
  register: fpm_conf
- name: start fpm-pool
  service:
    name: php8.0-fpm
    state: restarted
    enabled: yes
  when: fpm_conf.changed
# web apps folder
# set permissions
- name: fix folder perms
  file:
    path: /web/firefly
    state: directory
    owner: firefly
    group: www-data
    recurse: yes
- name: www-data folder
  file:
    path: /web/firefly/www-data/
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
# build environment vars file
- name: build environment file
  template:
    src: ../templates/.env.j2
    dest: /web/firefly/.env
    owner: firefly
    group: firefly
- name: nginx folder
  file:
    path: /web/firefly/nginx/
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
- name: nginx folder
  file:
    path: /web/firefly/nginx/tmp
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
- name: copy nginx config files
  copy:
    src: "../files/firefly-nginx.conf"
    dest: /etc/nginx/sites-enabled/firefly.conf
  register: nginx_conf
- name: start nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: nginx_conf.changed
# mailhog?
#https://github.com/mailhog/MailHog/releases/download/v1.0.1/MailHog_windows_amd64.exe

# One time only, you need to generate the secret APP_KEY:

# php artisan key:generate

# One time only, the storage/ directory must be linked to the application:

# php artisan storage:link

# Database migrations must be run:

# php artisan migrate --force

# If you want to enable support for location data:

# php artisan import:cities

# If you enabled ActivityPub federation:

# php artisan instance:actor

# If you enabled OAuth:

# php artisan passport:keys

# Routes should be cached whenever the source code changes or whenever you change routes:

# php artisan route:cache
# php artisan view:cache

# Every time you edit your .env file, you must run this command to have the changes take effect:

# php artisan config:cache
